name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: svelte-testing
      SENTRY_PROJECT: javascript-react-github-actions

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Install
        run: yarn

      - name: Build assets
        run: yarn run build

      - name: Sentry Release
        uses: getsentry/action-release@v1.2.1 #
        with:
          environment: production
          url_prefix: ~/static/js
          sourcemaps: build/static/js
          set_commits: skip
